apiVersion: v1
data:
  CLOUDINARY_API_KEY: NjU3ODU4NzU0Nzc2OTkx
  CLOUDINARY_API_SECRET: RC1DNjNFZmVObUo1MTZYT3ZwVV9pbTVEUWRF
  CLOUDINARY_CLOUD_NAME: ZHVwM3ltajNw
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfbEJicTl4QWc2TXJrQGVwLWFnZWQtYXJ0LWFiMjJjd3VkLXBvb2xlci5ldS13ZXN0LTIuYXdzLm5lb24udGVjaC9uZW9uZGI/c3NsbW9kZT1yZXF1aXJlJmNvbm5lY3Rpb25fbGltaXQ9NQ==
  EMAIL_HOST: c210cC5nb29nbGUuY29t
  EMAIL_PASS: cHppeW9nZmJqZnJjbWpueg==
  EMAIL_PORT: NDY1
  EMAIL_USER: dHVsc2lyaWphbDIwMTlAZ21haWwuY29t
  GEMINI_API_KEY: QUl6YVN5QWJfR25WX2QwQVZWTUVkSm1aZ2RpU0t6U3gzWDdmSE9F
  JWT_ACCESS_SECRET: c2VjcmV0
  JWT_REFRESH_SECRET: c2VjcmV0
  REDIS_URL: cmVkaXNzOi8vZGVmYXVsdDpBVk5TXzdyYzRDa2R1NDZxcS1RUDdIbGJAdmlkZW9hcHAtdmlkZW9hcHAuaC5haXZlbmNsb3VkLmNvbToxNDQxOA==
kind: Secret
metadata:
  name: videoapp-secrets
  namespace: videoapp
type: Opaque
