version: '3.8'
services:
  redis_test:
    image: redis:latest
    container_name: redis_test
    restart: always
    ports:
      - "6379:6379"
  postgres-test-db:
    image: postgres:15
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"   
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  app:
    build: .
    restart: always
    depends_on:
      postgres-test-db:
        condition: service_healthy
      redis_test:
        condition: service_started
    environment:
      REDIS_URL: "redis://redis_test:6379"
      DATABASE_URL: "postgresql://test_user:test_password@postgres-test-db:5432/test_db?schema=public"
      JWT_ACCESS_SECRET: "testing_access_secret"
      JWT_REFRESH_SECRET: "testing_refresh_secret"
      NODE_ENV: test
    ports:
      - "5002:5002"
    command: ["npm", "run", "dev"]
    volumes:
      - .:/app
      - /app/node_modules
      
volumes:
  pgdata_test: